services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: